services:
  web:
    build: .
    ports:
      - "3000:80"
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - ./storage:/rails/db
      - db_data:/rails/db
    restart: unless-stopped

volumes:
  db_data:
